clickhouse:
  host: "localhost"
  user: "default"
  password: ""
  database: "pmacct"
  table: "flows"

geoip:
  asn_db: "/etc/pmacct/GeoLite2-ASN.mmdb"
  city_db: "/etc/pmacct/GeoLite2-City.mmdb"

bgp:
  table_file: "/var/log/nfacctd/bgp_table.json"

kafka:
  brokers:
    - "localhost:9092"
  topic: "netflow"
  group_id: "flowenricher"

dns:
  nameserver: "1.1.1.1"

timezone: "Europe/Athens"
debug: true

enrich: "none"
# could be geoip, bgp, ptr or none

