
bgp:
  table_file: "/var/log/nfacctd/bgp_table.json"
  bgp_listener:
    enabled: true
    listen_ip: "0.0.0.0"
    asn: 216285
    router_id: "84.54.49.1"
    max_peers: 2


clickhouse:
  host: "localhost"
  user: "default"
  password: ""
  database: "pmacct"
  table: "flows"


geoip:
  asn_db: "/etc/pmacct/GeoLite2-ASN.mmdb"
  city_db: "/etc/pmacct/GeoLite2-City.mmdb"


kafka:
  brokers:
    - "localhost:9092"
  topic: "netflow"
  group_id: "flowenricher-group"

dns:
  nameserver: "1.1.1.1"

timezone: "Europe/Athens"

debug: false

enrich: "geoip, bgp"
# could be geoip, bgp, ptr or none


insert:
  batch_size: 200
  flush_interval_ms: 1000
