! nfacctd configuration
daemonize: false
pidfile: /var/run/nfacctd.pid
syslog: daemon
logfile: /var/log/nfacctd/daemon.log

nfacctd_ip: 0.0.0.0
nfprobe_receiver: true
nfacctd_port: 2055


! Enable BGP enrichment
bgp_daemon: true
bgp_daemon_ip: 0.0.0.0
bgp_daemon_max_peers: 4
bgp_daemon_as: 65000
nfacctd_as: bgp
bgp_agent_map: /etc/pmacct/agent_map.map
pmacctd_as: bgp


geoipv2_file: /etc/pmacct/GeoLite2-Country.mmdb

as_path_encode_as_array: true

aggregate: timestamp_start, proto, tcpflags, tos, src_host, src_port, src_host_country, dst_host, dst_port, dst_host_country, peer_src_as, peer_dst_as, as_path

!plugins: print
!print_output: json
!print_refresh_time: 30
!print_output_file: /var/log/nfacctd/flows.json


plugins: kafka
kafka_broker_host: 127.0.0.1
kafka_broker_port: 9092
kafka_topic: netflow
kafka_format: json
kafka_refresh_time: 2
kafka_history: 5
kafka_partition_key: src_host

# Προαιρετικά
kafka_async: true
kafka_debug: false


!debug: true

bgp_table_dump_file: /var/log/nfacctd/bgp_table.json
bgp_table_dump_refresh_time: 120


